# docker-compose.yml
version: '3'

services:

  migrate:
    build: .
    container_name: 'migrate'
    command: >
      /bin/bash -c "
      python3 manage.py makemigrations --force-color --no-input -v 3
      && python3 manage.py makemigrations --force-color --no-input -v 3 backend
      && python3 manage.py makemigrations --force-color --no-input -v 3 frontend
      && python3 manage.py migrate --force-color -v 3
      && python3 manage.py collectstatic --noinput
      && python3 manage.py createsuperuser --noinput"
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DEBUG=1
      - MAX_UNIQUE_LINKS_PER_DAY=5
    volumes:
      - .:/app
    networks:
      - internal

  gunicorn:
    image: duolingofree_migrate
    container_name: 'gunicorn'
    command: /bin/bash -c "python3 -m gunicorn -b 0.0.0.0:80 DuolingoFree.wsgi --reload"
    environment:
      - DEBUG=1
    volumes:
      - .:/app
    expose:
      - 80
    ports:
      - 80:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gunicorn.rule=Host(`duo.egorovegor.ru`)"
      - "traefik.http.middlewares.test-redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.middlewares.test-redirectscheme.redirectscheme.permanent=true"
    networks:
      - internal
      - traefik

  puller:
    image: duolingofree_migrate
    container_name: 'puller'
    command: /bin/bash -c "python3 /app/manage.py puller"
    volumes:
      - .:/app
    depends_on:
      - redis
      - celery
      - migrate
    networks:
      - internal

  redis:
    image: "redis:alpine"
    container_name: 'redis'
    networks:
      - internal

  celery:
    image: duolingofree_migrate
    container_name: 'celery'
    command: /bin/bash -c "python3 -m celery -A DuolingoFree worker -c 1 -l INFO"
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - internal

  flower:
    image: duolingofree_migrate
    container_name: 'flower'
    command: /bin/bash -c "python3 -m celery --broker=redis://redis:6379/0 flower --address=0.0.0.0 --port=5555"
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - internal

  selenium:
    image: selenium/standalone-firefox:4.1.2
    container_name: 'selenium'
    environment:
      - GRID_MAX_SESSION=1
    volumes:
      - .:/app
    networks:
      - internal

networks:
  traefik:
    external: true
  internal:
    external: false
