# docker-compose.yml
version: '3'

services:

  migrate:
    build: .
    container_name: 'migrate'
    command: >
      /bin/bash -c "
      python3 manage.py makemigrations --force-color --no-input -v 3
      && python3 manage.py makemigrations --force-color --no-input -v 3 backend
      && python3 manage.py makemigrations --force-color --no-input -v 3 frontend
      && python3 manage.py migrate --force-color -v 3
      && python3 manage.py collectstatic --noinput
      && python3 manage.py createsuperuser --noinput"
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DEBUG=1
    volumes:
      - .:/app
    networks:
      - internal

  gunicorn:
    image: duolingofree_migrate
    container_name: 'gunicorn'
    command: /bin/bash -c "python3 -m gunicorn -b 0.0.0.0:8000 DuolingoFree.wsgi --reload"
    environment:
      - DEBUG=1
    volumes:
      - .:/app
    ports:
      - 8000:8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gunicorn.entrypoints=websecure"
      - "traefik.http.routers.gunicorn.rule=Host(`duo.egorovegor.ru`)"
      - "traefik.http.routers.gunicorm.entrypoints=websecure"
      - "traefik.http.routers.gunicorn.tls.certresolver=myresolver"
    networks:
      - internal
      - traefik

  puller:
    image: duolingofree_migrate
    container_name: 'puller'
    command: /bin/bash -c "python3 /app/manage.py puller"
    volumes:
      - .:/app
    depends_on:
      - redis
      - celery
      - migrate
    networks:
      - internal

  queue_reset:
    image: duolingofree_migrate
    container_name: 'queue_reset'
    command: /bin/bash -c "python3 /app/manage.py queue_reset"
    volumes:
      - .:/app
    depends_on:
      - migrate
    networks:
      - internal

  redis:
    image: "redis:alpine"
    container_name: 'redis'
    networks:
      - internal

  celery:
    image: duolingofree_migrate
    container_name: 'celery'
    command: /bin/bash -c "python3 -m celery -A DuolingoFree worker -c 1 -l INFO"
    environment:
      - TELEGRAM_BOT_TOKEN=TOKEN_HERE
      - TELEGRAM_CHAT_ID=-CHAT_ID_HERE
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - internal

  flower:
    image: mher/flower
    container_name: flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_BASIC_AUTH=duolingo:free
      - FLOWER_PORT=5555
      - FLOWER_PERSISTENT=True
      - FLOWER_STATE_SAVE_INTERVAL=10000
      - FLOWER_DB=/etc/db/flower.db
    ports:
      - "5555:5555"
    volumes:
      - .:/app
      - .:/etc/db/
    depends_on:
      - redis
    networks:
      - internal

  selenium:
    image: selenium/standalone-firefox:4.1.2
    container_name: 'selenium'
    hostname: 'selenium'
    environment:
      - GRID_MAX_SESSION=5
      - GRID_TIMEOUT=120
      - GRID_BROWSER_TIMEOUT=120
    volumes:
      - .:/app
    ports:
      - "5900:5900"
    networks:
      - internal

networks:
  traefik:
    external: true
  internal:
    external: false
